### ISSUE TITLE
Camera doesn't work with oss kernel

### ISSUE THREAD

**Issue by DanWard** [thune-xiaobai/android_device_xiaomi_sagit#10]
Camera doesn't work in any application with the OSS kernel. I'm using your kernel fork to compile, and have tried both 7.9.14 China Dev and 7.9.22 Global Dev firmwares. 

Logcats below:
Snap camera crash - https://pastebin.com/raw/RGEVYV30
Google camera crash - https://pastebin.com/raw/EWbzBpNg

**Comment by coderstory** [comment]
he know it

**Comment by thune-xiaobai** [comment]
baseline of this OSS kernel is too old.
find a miui rom with Meta_Build_Id on firmware matches MSM8998.LA.1.1.r1-*
replace all camera blobs with it,then camera works

**Comment by DanWard** [comment]
Cool easy fix then. Where can I find the Meta_Build_Id?
Appreciate the help.

**Comment by coderstory** [comment]
开源的代码的最后更新日期 匹配 miui版本发布日期 233333

**Comment by DanWard** [comment]
@coderstory - what date is 233333? I've got it working with China Dev 7.5.5.
Edit: Never mind, I see that 2333 translates to 哈哈哈.
