### ISSUE TITLE
IR Blaster not working seLinux Enforcing

### ISSUE THREAD

**Issue by gschuurman** [thune-xiaobai/android_device_xiaomi_sagit#11]
With the new config of seLinux enforcing the ir blaster does not work at all, this can be fixed by changing to Permissive.
Lookintg at the Dmesg output with Permissive(tollerant) seLinux i get this warning even though its working now
`  [171.449886] type=1400 audit(1508343558.403:59): avc: denied { read write } for pid=3217 comm="Binder:1624_C" name="peel_ir" dev="tmpfs" ino=23049 scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=0`

I suggest to finetune the sePolicy some more.
Maybe this link can help: [http://searchmobilecomputing.techtarget.com/tip/How-to-manage-and-modify-SE-Android](url)

**Comment by thune-xiaobai** [comment]
thx, I will correct sepolicy for this soon.

**Comment by thune-xiaobai** [comment]
fixed.
