### ISSUE TITLE
Build issue with prebuilt

### ISSUE THREAD

**Issue by DanWard** [thune-xiaobai/android_device_xiaomi_sagit#2]
Hi,

I'm having a build issue when attempting to build this device tree using a prebuilt kernel.
`ninja: error: '/home/daniel/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ/usr', needed by '/home/daniel/android/lineage/out/target/product/sagit/obj/SHARED_LIBRARIES/libbt-vendor_intermediates/src/bt_vendor_persist.o', missing and no known rule to make it`

Disabling bluetooth only changes the error to ALSA related. I have 2 Mi 6's and are happy to test any solutions.
If you have a custom manifest.xml for the msm8998 kernel and audio related libraries could you also share it?

Thanks,
Daniel

**Comment by thune-xiaobai** [comment]
download kernel source from codeaurora,and prebuilt kernel is needed

**Comment by DanWard** [comment]
I have in my manifest.xml.
`<project path="kernel/xiaomi/msm8998" remote="caf" name="kernel/msm-4.4" revision="e64aca1e29eee783187a98a5a4f34101cd045b1e" upstream="refs/heads/kernel.lnx.4.4.r15-rel"/>`
Would this be right?

This then gives me the error below:
`ninja: error: '/home/daniel/android/lineage/out/target/product/sagit/obj/lib/libqdutils.so.toc', needed by '/home/daniel/android/lineage/out/target/product/sagit/obj/SHARED_LIBRARIES/libsurfaceflinger_intermediates/LINKED/libsurfaceflinger.so', missing and no known rule to make it`

Thanks,
Daniel

**Comment by thune-xiaobai** [comment]
On msm8996,It's defined here:
https://github.com/LineageOS/android_hardware_qcom_display/blob/cm-14.1-caf-8996/libqdutils/Android.mk
But los doesn't suppport msm8998 right now
Add it from caf

**Comment by DanWard** [comment]
Awesome, I have the CAF one installed now. But I have an environment issue that I will try and fix today. After running 'brunch sagit':
`Starting build with ninja
ninja: Entering directory `.'
[  0% 84/47892] Building Kernel Config
FAILED: /bin/bash -c "(make -j16  CFLAGS_MODULE=\"-fno-pic\" -C kernel/xiaomi/msm8998 O=/mnt/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ ARCH=arm64 CROSS_COMPILE=\"/usr/bin/ccache aarch64-linux-acho \"Overriding kernel config with ''\";                       echo  >> /mnt/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ/.config;                  make -j16 -C kernel/xiaomi/msm8998 O=/mnt/androdroid-\" oldconfig; fi ) && (make -j16 -C kernel/xiaomi/msm8998 O=/mnt/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ ARCH=arm64 CROSS_COMPILE=\"/usr/bin/ccache aarch64-linux-android-\" savedefconfil/xiaomi/msm8998/scripts/kconfig/merge_config.sh -m -O /mnt/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ /mnt/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ/.config kernel/xiaomi/msm8998/product/sagit/obj/KERNEL_OBJ ARCH=arm64 CROSS_COMPILE=\"/usr/bin/ccache aarch64-linux-android-\" KCONFIG_ALLCONFIG=/mnt/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ/.config alldefconfig; fi )"
make: Entering directory `/mnt/android/lineage/kernel/xiaomi/msm8998'
make[1]: Entering directory `/mnt/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ'
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/zconf.tab.o
scripts/kconfig/zconf.tab.c:211:24: fatal error: zconf.hash.c: No such file or directory
 #include "zconf.hash.c"
                        ^
compilation terminated.
make[2]: *** [scripts/kconfig/zconf.tab.o] Error 1
make[1]: *** [msm_defconfig] Error 2
make[1]: Leaving directory `/mnt/android/lineage/out/target/product/sagit/obj/KERNEL_OBJ'
make: *** [sub-make] Error 2
make: Leaving directory `/mnt/android/lineage/kernel/xiaomi/msm8998'
[  0% 84/47892] host C++: libc++_static_32 <= external/libcxx/src/algorithm.cpp
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1
make: Leaving directory `/mnt/android/lineage'`

**Comment by DanWard** [comment]
Additionally if I run 'export ARCH=arm64' and then 'make msm_defconfig' then the above issue stops and it compiles heaps further. But still fails here: https://pastebin.com/sJ0fMBa4. Any help would be appreciated.

**Comment by DanWard** [comment]
Alright after a few days of trying, I'm stuck again about 50% through the build process:
`hardware/qcom/media-caf/msm8998/mm-video-v4l2/vidc/venc/inc/video_encoder_device_v4l2.h:39:10: fatal error: 'VQZip.h' file not found
#include "VQZip.h"
         ^
1 error generated.`

I have these projects from CAF now:
` <project remote="caf" groups="qcom,default" name="platform/hardware/qcom/audio" path="hardware/qcom/audio-caf/msm8998" revision="8965eec9abd1eca51d5547c558ee5d999396e087" upstream="refs/heads/audio-userspace.lnx.2.2.r3-rel"/>
  <project groups="qcom,default" name="platform/hardware/qcom/media" path="hardware/qcom/media-caf/msm8998" remote="caf" revision="eea4f168f2317b8f6fb8793c8fbf23b9d6f6a338" upstream="refs/heads/video-userspace.lnx.2.1.r16-rel"/>
  <project groups="qcom,default" name="platform/hardware/qcom/display" path="hardware/qcom/display-caf/msm8998" remote="caf" revision="5ea011582f12e3e0157e803ceae626ec4e049021" upstream="refs/heads/display.lnx.3.0.r16-rel"/>
  <project path="kernel/xiaomi/msm8998" remote="caf" name="kernel/msm-4.4" revision="0dc8af9c1978ecd0f57bd8d2d1c1fbb13a0eb241" upstream="refs/heads/kernel.lnx.4.4.r15-rel"/>
  <project remote="caf" groups="pdk" name="platform/external/kernel-headers" path="external/kernel-headers" revision="54495e7569aeb1f571f1e39ca67532cd3f4eace5" upstream="refs/heads/android-external.lnx.2.0.r15-rel"/>`

Thanks!

**Comment by DanWard** [comment]
Alright after a few days of trying, I'm stuck again about 50% through the build process:

> `hardware/qcom/media-caf/msm8998/mm-video-v4l2/vidc/venc/inc/video_encoder_device_v4l2.h:39:10: fatal error: 'VQZip.h' file not found`
> `#include "VQZip.h"`
> `         ^`
> `1 error generated.`

I have these projects from CAF now:

> `<project remote="caf" groups="qcom,default" name="platform/hardware/qcom/audio" path="hardware/qcom/audio-caf/msm8998" revision="8965eec9abd1eca51d5547c558ee5d999396e087" upstream="refs/heads/audio-userspace.lnx.2.2.r3-rel"/>`
> `<project groups="qcom,default" name="platform/hardware/qcom/media" path="hardware/qcom/media-caf/msm8998" remote="caf" revision="eea4f168f2317b8f6fb8793c8fbf23b9d6f6a338" upstream="refs/heads/video-userspace.lnx.2.1.r16-rel"/>`
> `<project groups="qcom,default" name="platform/hardware/qcom/display" path="hardware/qcom/display-caf/msm8998" remote="caf" revision="5ea011582f12e3e0157e803ceae626ec4e049021" upstream="refs/heads/display.lnx.3.0.r16-rel"/>`
> `<project path="kernel/xiaomi/msm8998" remote="caf" name="kernel/msm-4.4" revision="0dc8af9c1978ecd0f57bd8d2d1c1fbb13a0eb241" upstream="refs/heads/kernel.lnx.4.4.r15-rel"/>`

Thanks!

Edit: reposted due to formatting errors.
Edit 2: if I disable VQZip, then I get the same error but with `pqstats.h` instead.

**Comment by DanWard** [comment]
@thune-xiaobai I have Lineage building now, but not booting. I've played around with the selinux contexts to get it to work but no result. The last_kmsg is attached: https://pastebin.com/tupthhRk. Please help.

**Comment by thune-xiaobai** [comment]
display is bad
delete libsdm-extensions.so and try again

**Comment by DanWard** [comment]
Is this the correct caf release to use: 
 June 15, 2017 	 LA.UM.5.8.r1-02000-8x98.0 	 msm8998 	LA.UM.5.8.r1-02000-8x98.0.xml	 07.01.02 
?

Also would the libsdm issue be related to the VQZip and PQ errors from above?

**Comment by thune-xiaobai** [comment]
no

**Comment by DanWard** [comment]
Which would be the correct caf release? https://wiki.codeaurora.org/xwiki/bin/QAEP/release

**Comment by thune-xiaobai** [comment]
seriously u can build a bootable lineageos on this tag,but 5.8.r1 has much difference between 5.7.r1.
by the way,is it booting now?

**Comment by DanWard** [comment]
I'm not at home at the moment, so I can't do a rebuild until tonight.
I'll change the tags when I get home so I use the 5.7r1 instead of the 5.8r1. 
I had a problem with the audio-caf with invalid memory references, did you have that problem too?

I really really appreciate you helping me with this, is there a better way to contact you? and do you have somewhere I can donate to you?

Edit: these are now my entries into manifest.xml:
- `<remote fetch="https://source.codeaurora.org/quic/la/" name="caf" review="codeaurora.org"/>`
- `<project remote="caf" groups="qcom,default" name="platform/hardware/qcom/audio" path="hardware/qcom/audio-caf/msm8998" revision="cc89b477ae9f07fec5c92318f0f74f243e02ca67" upstream="refs/heads/audio-userspace.lnx.2.1.r13-rel"/>`
- `<project remote="caf" groups="qcom,default" name="platform/hardware/qcom/media" path="hardware/qcom/media-caf/msm8998" revision="4d3fa2da4eac23b6ab6f04a3266f6a234a8c5640" upstream="refs/heads/video-userspace.lnx.2.1.r13-rel"/>`
- `<project remote="caf" groups="qcom,default" name="platform/hardware/qcom/display" path="hardware/qcom/display-caf/msm8998" revision="cc00c61b849b68338cd325084f73f12ed0ceeb24" upstream="display.lnx.3.0.r13-rel"/>`
- `<project remote="caf" name="kernel/msm-4.4" path="kernel/xiaomi/msm8998" revision="d51b6bb2a50879a1ebc426c5f30563f74501bd4f" upstream="kernel.lnx.4.4.r13-rel"/>`
- `<project remote="caf" groups="pdk" name="platform/external/kernel-headers" path="external/kernel-headers" revision="54495e7569aeb1f571f1e39ca67532cd3f4eace5" upstream="android-external.lnx.2.0.r13-rel"/>`
taken from: https://source.codeaurora.org/quic/la/platform/manifest/tree/LA.UM.5.7.r1-09700-8x98.0.xml?h=LA.UM.5.7.r1-09700-8x98.0

**Comment by DanWard** [comment]
@thune-xiaobai - I used the ./extract-files.sh on the system.img from http://bigota.d.miui.com/7.6.8/sagit_images_7.6.8_20170608.0000.00_7.1_cn_e9c5fc9533.tgz.
Then this is everything I needed to do in order to get it to compile:

- Device: Change target from sagit_defconfig to msm_defconfig
- Device: Set USE_CUSTOM_AUDIO_POLICY to 0
- Kernel: Kernel disable -Wall, remove -Werror implicit
- External: Add IFNAMSIZ to external/ebtables/include/ebtables_u.h
- Display-caf: Remove liblight product, as device has it already
- Media-caf: Update include directories, -caf/msm8998
- Media-caf: Remove duplicated enums in ./mm-core/inc/QCMetaData.h
- Media-caf: Disable vqzip and pq for msm8998
- Audio-caf: Update include directories, -caf/msm8998
- Audio-caf: Copy hardware/qcom/audio-caf/msm8996/hal/audio_extn/sound_trigger_prop_intf.h -> hardware/qcom/audio-caf/msm8998/hal/audio_extn/
- Audio-caf: Remove references to invalid variables in ./hal/audio_extn/soundtrigger.c
- Audio-caf: Remove -Wall from makefile, warnings =/= errors

Edit: new last_kmsg from latest build https://pastebin.com/eiLqmTNm

**Comment by DanWard** [comment]
Progress! It now displays the Lineage boot animation but does not appear to go any further - I have wiped data and cache. ADB doesn't start, and the kmsg log is now https://pastebin.com/ky7yXqa4.

Edit: by the way, I deleted audioserver again because it was giving me the following error message repeatedly:
> [  145.431485] init: Starting service 'audioserver'...
> [  145.572292] audioserver[1931]: unhandled level 1 translation fault (11) at 0x000000fc, esr 0x92000005
> [  145.572298] pgd = ffffffc16b2a5000
> [  145.572302] [000000fc] *pgd=0000000000000000, *pud=0000000000000000
> [  145.572308] 
> [  145.572313] CPU: 5 PID: 1931 Comm: audioserver Tainted: G        W       4.4.21-perf-g6a9ee37d-05846-g52167b2 #1
> [  145.572316] Hardware name: Qualcomm Technologies, Inc. MSM 8998 v2.1 MTP (DT)
> [  145.572320] task: ffffffc09d5b2580 ti: ffffffc159024000 task.ti: ffffffc159024000
> [  145.572324] PC is at 0xe800bad6
> [  145.572326] LR is at 0xe800b937
> [  145.572329] pc : [<00000000e800bad6>] lr : [<00000000e800b937>] pstate: 600f0030
> [  145.572332] sp : 00000000ff957d88
> [  145.572335] x12: 00000000e81bd944 
> [  145.572339] x11: 00000000ff957e04 x10: 00000000ff957da8 
> [  145.572344] x9 : 00000000e78178c0 x8 : 00000000e804f847 
> [  145.572351] x7 : 00000000e7813100 x6 : 00000000e73b8df0 
> [  145.572357] x5 : 00000000e7817b80 x4 : 00000000e804f89e 
> [  145.572362] x3 : 0000000000000080 x2 : 0000000000000000 
> [  145.572367] x1 : 00000000ff957e04 x0 : 00000000ff957fb4 
> [  145.572372] 
> [  145.573878] init: Service 'audioserver' (pid 1931) killed by signal 11
> [  145.573888] init: Service 'audioserver' (pid 1931) killing any children in process group

Edit edit: this is a paste of the kmsg log with audioserver https://pastebin.com/PdgsLWn6

**Comment by thune-xiaobai** [comment]
Device: Set USE_CUSTOM_AUDIO_POLICY to 0
It's wrong to do with this.
add this flag to BoardConfig.mk: AUDIO_FEATURE_ENABLED_FM_POWER_OPT := true
And try to compile again.
By the way, delete qti-telephony-common.jar.also, u need to compile an eng version, not userdebug

**Comment by DanWard** [comment]
I have compiled it with:
- USE_CUSTOM_AUDIO_POLICY := 1
- AUDIO_FEATURE_ENABLED_FM_POWER_OPT := true
- brunch sagit eng

I haven't deleted qti-telephony-common.jar yet, I'm going to see if it boots with it first tonight. What would be the reason that it needs that deleted?

Edit: now compiles with vqzip and gpustats - `Reverted: Media-caf: Disable vqzip and pq for msm899`.

**Comment by DanWard** [comment]
ADB now works, and I don't need to change the custom audio policy - but the device still doesn't boot:
Logcat https://pastebin.com/5ir8HHUQ.

Edit: to get it to boot (temporarily) I used `BOARD_USES_GENERIC_AUDIO := true`. I deleted qti-telephony-common.jar due to com.android.phone crash.

**Comment by DanWard** [comment]
I pulled your latest changes and tried again, device does not boot with audioserver tainted.
This is how I got it to compile, is this right?
https://github.com/DanWard/platform-hardware-qcom-media-caf-msm8998/commit/798ff0edb99017d7ff23f62a27b908a9e1fe8460
https://github.com/DanWard/android_device_xiaomi_sagit/commit/750f8d8599a4414b4c3783531aa202d2b44a7c38
https://github.com/DanWard/android_external_ebtables/commit/fd9db10e523d107a77370a25ba163488ae1c51b6
https://github.com/DanWard/platform-hardware-qcom-display-caf-msm8998/commit/a9622e32d08b7cdd6042462fc1e5414e3a478e13
https://github.com/DanWard/platform-hardware-qcom-audio-caf-msm8998/commit/5a982792819f3e68715e1dc25c074fdd27d5b0f2
https://github.com/DanWard/android/commit/22434df3ab35855131e453d38dece663be48f50a

**Comment by rancidfrog** [comment]
@DanWard 
I am currently downloading sources to compile and was wondering,
Where did you find mentioned commits to fix compile?

**Comment by thune-xiaobai** [comment]
#00 pc 00039ad6  /system/lib/libaudiopolicymanagerdefault.so
I think this issue is still related to flag USE_CUSTOM_AUDIO_POLICY,recommand you to do a clean build and,this device is currently not compatible with fbe,format data is needed.

**Comment by DanWard** [comment]
@thune-xiaobai - did a clean build this morning, took 2 hours to compile everything. Formatted data using official TWRP. Still the same issue with `#00 pc 00039ad6  /system/lib/libaudiopolicymanagerdefault.so`
Dmesg - https://pastebin.com/cDYNK0BU
Logcat - https://pastebin.com/XZQhqM6i

@rancidfrog - I made them myself from the errors thrown in the build process, merging in LineageOS code where possible.

**Comment by thune-xiaobai** [comment]
I have uploaded audio/media/display changes to https://github.com/mi6devs, u can refer to this.
