### ISSUE TITLE
0702 Version Random MAC Address

### ISSUE THREAD

**Issue by Ricky-Hao** [thune-xiaobai/android_device_xiaomi_sagit#4]
1. Flash China Dev 7.6.29 via fastboot
2. Flash TWRP
3. Wipe Data
4. Flash Lineageos-0702 and OpenGapps

Expect: The MAC address as same as MIUI.
Real: Random MAC address, change at reboot every time

**Comment by thune-xiaobai** [comment]
does it change after you close and reopen wifi?

**Comment by Ricky-Hao** [comment]
@thune-xiaobai No change after reopen wifi. Only change on reboot.

**Comment by Ricky-Hao** [comment]
After turn on and turn off the Airplane mode, the wifi MAC changed.

**Comment by thune-xiaobai** [comment]
This issue has been fixed with OSS kernel
