### ISSUE TITLE
SIM card setting reset to default after reboot

### ISSUE THREAD

**Issue by Ricky-Hao** [thune-xiaobai/android_device_xiaomi_sagit#5]
Setting:
* Celluler data: Card2
* Calls: Card1
* SMS messages: Card1

Reboot devices.
Expect:  SIM card setting as same as before.
Actually: SIM card setting reset to default( All settings set to Card1).

PS: Also test after turn on and turn off Airplane mode, the SIM card setting no changed.

**Comment by thune-xiaobai** [comment]
cannot reproduce
